[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "moodstory-backend"
version = "0.1.0"
authors = [{name=""}]
dependencies = ["tensorflow", "numpy"]

[tool.setuptools.packages.find]
where = ["."]
